import type { Metadata } from "next";
import { Unbounded, Outfit, Fira_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const unbounded = Unbounded({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const firaSans = Fira_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Portfolio | Suyog Poudel",
  description: "Generated by create next app",
  keywords: [
    "Suyog Poudel",
    "web developer",
    "next.js dev",
    "react js dev",
    "portfolio",
    "ui/ux",
    "web developer portfolio",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${unbounded.className} ${outfit.className} ${firaSans.className} flex flex-col min-h-screen font-main antialiased bg-zinc-800 text-zinc-200`}
      >
        <nav className="fixed z-50 w-full">
          <Navbar />
        </nav>

        <main className="flex-1 flex justify-center items-center py-15">
          {children}
        </main>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
